name: LumaQA Cypress BDD Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean old artifacts
        run: npm run cy:clean

      - name: Run UI Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          record: false
          parallel: true
          group: 'UI Tests'
          spec: |
            cypress/e2e/features/ui/*.feature

      - name: Run API Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          record: false
          parallel: true
          group: 'API Tests'
          spec: |
            cypress/e2e/features/api/*.feature

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos