name: LumaQA Cypress BDD Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean old reports
        run: npm run cy:clean

      - name: Run Cypress tests
        run: npm run cy:run

      - name: Merge mochawesome reports
        if: always()
        run: |
          mkdir -p cypress/reports
          npm run cy:report:merge

      - name: Generate mochawesome HTML report
        if: always()
        run: npm run cy:report:generate

      - name: Upload videos & screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/**
            cypress/screenshots/**
          if-no-files-found: ignore

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html-report
          if-no-files-found: ignore

  deploy-report:
    needs: e2e
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download HTML report
        uses: actions/download-artifact@v4
        with:
          name: mochawesome-report
          path: public

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public